//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WebResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actividad.
        /// </summary>
        internal static string ACTIVIDAD {
            get {
                return ResourceManager.GetString("ACTIVIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación entre las actividades .
        /// </summary>
        internal static string ACTIVITIES_RELATION {
            get {
                return ResourceManager.GetString("ACTIVITIES_RELATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        internal static string APELLIDOS {
            get {
                return ResourceManager.GetString("APELLIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stochastic Earned Value.
        /// </summary>
        internal static string APP_TITLE {
            get {
                return ResourceManager.GetString("APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Proyecto.
        /// </summary>
        internal static string CREATE_PROJECT {
            get {
                return ResourceManager.GetString("CREATE_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion.
        /// </summary>
        internal static string DESCRIPCION {
            get {
                return ResourceManager.GetString("DESCRIPCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Destino.
        /// </summary>
        internal static string DESTINO {
            get {
                return ResourceManager.GetString("DESTINO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es obligatorio que todas las actividades tengan nombre..
        /// </summary>
        internal static string ERROR_ALTA_PROYECTO_PASO_DOS {
            get {
                return ResourceManager.GetString("ERROR_ALTA_PROYECTO_PASO_DOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es obligatorio seleccionar al menos una actividad destino para cada actividad origen..
        /// </summary>
        internal static string ERROR_ALTA_PROYECTO_PASO_TRES {
            get {
                return ResourceManager.GetString("ERROR_ALTA_PROYECTO_PASO_TRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es necesario rellenar todos los campos.
        /// </summary>
        internal static string ERROR_FILL_FIELDS {
            get {
                return ResourceManager.GetString("ERROR_FILL_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario o la contraseña son incorrectos o no existen..
        /// </summary>
        internal static string ERROR_LOGIN {
            get {
                return ResourceManager.GetString("ERROR_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario ya existe.
        /// </summary>
        internal static string ERROR_USER_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("ERROR_USER_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string ESPAÑOL {
            get {
                return ResourceManager.GetString("ESPAÑOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se han encontrado elementos..
        /// </summary>
        internal static string GRIDVIEW_EMPTY_TEXT {
            get {
                return ResourceManager.GetString("GRIDVIEW_EMPTY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        internal static string INGLES {
            get {
                return ResourceManager.GetString("INGLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        internal static string NEXT {
            get {
                return ResourceManager.GetString("NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string NOMBRE {
            get {
                return ResourceManager.GetString("NOMBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string NOMBRE_ACTIVIDAD {
            get {
                return ResourceManager.GetString("NOMBRE_ACTIVIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Proyecto.
        /// </summary>
        internal static string NOMBRE_PROYECTO {
            get {
                return ResourceManager.GetString("NOMBRE_PROYECTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº Actividades.
        /// </summary>
        internal static string NUM_ACTIVIDADES {
            get {
                return ResourceManager.GetString("NUM_ACTIVIDADES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Origen.
        /// </summary>
        internal static string ORIGEN {
            get {
                return ResourceManager.GetString("ORIGEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 4.
        /// </summary>
        internal static string PASO_CUATRO {
            get {
                return ResourceManager.GetString("PASO_CUATRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 2.
        /// </summary>
        internal static string PASO_DOS {
            get {
                return ResourceManager.GetString("PASO_DOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 3.
        /// </summary>
        internal static string PASO_TRES {
            get {
                return ResourceManager.GetString("PASO_TRES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paso 1.
        /// </summary>
        internal static string PASO_UNO {
            get {
                return ResourceManager.GetString("PASO_UNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrate.
        /// </summary>
        internal static string REGISTER {
            get {
                return ResourceManager.GetString("REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        internal static string REGISTER_CONTINUAR {
            get {
                return ResourceManager.GetString("REGISTER_CONTINUAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes usuario? Por favor.
        /// </summary>
        internal static string REGISTER_INFO {
            get {
                return ResourceManager.GetString("REGISTER_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        internal static string USER {
            get {
                return ResourceManager.GetString("USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has sido registrado correctamente..
        /// </summary>
        internal static string USUARIO_REGISTRADO {
            get {
                return ResourceManager.GetString("USUARIO_REGISTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Proyectos.
        /// </summary>
        internal static string VIEW_PROJECTS {
            get {
                return ResourceManager.GetString("VIEW_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        internal static string VOLVER {
            get {
                return ResourceManager.GetString("VOLVER", resourceCulture);
            }
        }
    }
}
